source 'https://rubygems.org'

# https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/
gem 'github-pages', '>= 226', group: :jekyll_plugins

# https://jekyllrb.com/docs/windows/#time-zone-management
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end
# https://jekyllrb.com/docs/windows/#auto-regeneration
gem 'wdm', '~> 0.1.1', :install_if => Gem.win_platform?

# gem 'activesupport', '>= 7.0.2.3'
gem 'activesupport', '>= 4'
gem 'nokogiri', '>= 1.13.4'
